name: Update WoW Midcap Smallcap to Google Sheet

on:
  schedule:
    - cron: '0 1 * * 1-6'
  workflow_dispatch:

jobs:
  update-sheet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Debug and install dependencies
        run: |
          echo "===== Thư mục hiện tại ====="
          pwd
